# Generated by Django 4.0.3 on 2022-05-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_image_question_image_result_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(null=True, upload_to='answer_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.ImageField(null=True, upload_to='result_images/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
